-- This file should undo anything in `up.sql`

DROP TABLE LX_USER_AUTHS;
DROP TABLE LX_ROLES_USERS;
DROP TABLE LX_CLASSES_USERS;
DROP TABLE LX_ACTIVITIES_USERS;
DROP TABLE LX_USERS;
DROP TABLE LX_ROLES;
DROP TABLE LX_CLASSES;
DROP TABLE LX_ACTIVITIES;
DROP TABLE LX_BULLETINS;