-- YOUR SQL GOES HERE

CREATE TABLE LX_USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    BIRTHDAY DATE,
    HEIGHT SMALLINT DEFAULT 1 CHECK (HEIGHT > 0),
    WEIGHT SMALLINT DEFAULT 1 CHECK (HEIGHT > 0),
    STATUS CHAR(1) DEFAULT 0,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE LX_USER_AUTHS(
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER REFERENCES LX_USERS(ID),
    IDENTITY_TYPE CHAR(1) DEFAULT '0',
    IDENTIFIER VARCHAR(255),
    CREDENTIAL VARCHAR(255),
    TOKEN VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE LX_ROLES(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE LX_ROLES_USERS(
    ID SERIAL PRIMARY KEY,
    ROLE_ID INTEGER REFERENCES LX_ROLES(ID),
    USER_ID INTEGER REFERENCES LX_USERS(ID)
);

CREATE TABLE LX_CLASSES(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ALIAS_NAME VARCHAR(255),
    NICK_NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE LX_CLASSES_USERS(
    ID SERIAL PRIMARY KEY,
    CLASS_ID INTEGER REFERENCES LX_CLASSES(ID),
    USER_ID INTEGER REFERENCES LX_USERS(ID)
);

CREATE TABLE LX_ACTIVITIES(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL,
    FIELDS JSONB,
    CONTENT_RAW VARCHAR,
    CONTENT_HTML VARCHAR,
    STATUS CHAR(1) DEFAULT '0',
    VIEW_COUNT INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE LX_ACTIVITIES_USERS(
ID SERIAL PRIMARY KEY,
    ACTIVITIE_ID INTEGER REFERENCES LX_ACTIVITIES(ID),
    USER_ID INTEGER REFERENCES LX_USERS(ID),
    FIELD1 VARCHAR(255),
    FIELD2 VARCHAR(255),
    FIELD3 VARCHAR(255),
    FIELD4 VARCHAR(255),
    FIELD5 VARCHAR(255),
    FIELD6 VARCHAR(255),
    FIELD7 VARCHAR(255),
    FIELD8 VARCHAR(255),
    FIELD9 VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE LX_BULLETINS(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL,
    CONTENT_RAW VARCHAR,
    CONTENT_HTML VARCHAR,
    STATUS CHAR(1) DEFAULT '0',
    VIEW_COUNT INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);